[tool.poetry]
name = "pdns-distribute-docs"
version = "0.1.0"
description = ""
authors = ["linxside <noreply@linxsi.de"]

[tool.poetry.dependencies]
python = "^3.8"
mkdocs = "*"
mkdocs-material = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
